### ISSUE TITLE
Introduce command line option for uniform input error

### ISSUE THREAD

**Issue by Himeshi** [fp-analysis/klee#44]
In order to obtain error expressions containing multiple input errors, the current behavior requires providing the --pareto command line option. However the default behavior should allow for obtaining error expressions for programs with multiple input variables and multiple input errors even if pareto optimality is not computed.

Therefore remove the pareto option and introduce a new option, --uniform-input-error to allow pareto optimal computation when multiple input errors are defined.

**Comment by domainexpert** [comment]
Resolved via #45.
