### ISSUE TITLE
Keep track of error expressions of all program variables in a global map

### ISSUE THREAD

**Issue by Himeshi** [fp-analysis/klee#71]
At present, to get the error expressions out for the program variables, klee_bound_error calls must be inserted into the program. To reduce manual intervention and automate the process even further, keep track of program variables (with their local allocation)  and their error expressions and for each path output the final expression when the klee execution has finished.

**Comment by domainexpert** [comment]
@Himeshi Do you have an example for testing if one is to implement this feature?

**Comment by Himeshi** [comment]
@domainexpert Sorry, saw this comment only today. I was working on this and I tested it with [add_test.c](https://github.com/fp-analysis/fp-examples/blob/master/basic/add_test.c) and it seems to be working fine. However for arrays it doesn't seem to be producing the expressions correctly, which is what I'm debugging now.

There is a WIP pull request here: https://github.com/fp-analysis/klee/pull/80

**Comment by domainexpert** [comment]
Resolved via #80.
